/*
 * This file is auto-generated. Do not modify it manually.
 * Generated by AstGenerator at 30-08-2025 12:52:41
 */

#nullable enable
namespace FluxInterpreter;

public abstract class Stmt
{
    public interface IVisitor
    {
        void VisitBlockStmt(Block stmt);
        void VisitfcExpressionStmt(fcExpression stmt);
        void VisitPrintStmt(Print stmt);
        void VisitVarStmt(Var stmt);
    }

    public class Block(List<Stmt> statements) : Stmt
    {
        public List<Stmt> Statements { get; } = statements;

        public override void Accept(IVisitor visitor)
        {
            visitor.VisitBlockStmt(this);
        }
    }

    public class fcExpression(Expr expression) : Stmt
    {
        public Expr Expression { get; } = expression;

        public override void Accept(IVisitor visitor)
        {
            visitor.VisitfcExpressionStmt(this);
        }
    }

    public class Print(Expr expression) : Stmt
    {
        public Expr Expression { get; } = expression;

        public override void Accept(IVisitor visitor)
        {
            visitor.VisitPrintStmt(this);
        }
    }

    public class Var(Token name, Expr? initializer) : Stmt
    {
        public Token Name { get; } = name;
        public Expr? Initializer { get; } = initializer;

        public override void Accept(IVisitor visitor)
        {
            visitor.VisitVarStmt(this);
        }
    }


    public abstract void Accept(IVisitor visitor);
}
